koparion/koparion/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

koparion/store/urls.py
from django.urls import path

from . import views

app_name = 'store'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('search/', views.SearchPageView.as_view(), name='search'), # url to search page
    path('all-books/', views.AllBooksPageView.as_view(), name='all_books'), #a url to all books
    path('book/id/slug/', views.DetailPageView.as_view(), name='book_detail'), # url to a specific book
    path('register/', views.register, name='registeration'), # url to user registration page
    path('login/', views.login_view, name='login'), # url to user login page
    path('logout/', views.logout_view, name='logout'),


    path('cart-add/', views.cart_add, name='cart_add'), # adding books to the cart
    path('cart-summary/', views.cart_summary, name='cart_summary'), # summary of the cart
    path('checkout/', views.checkout_view, name='checkout'),
]

koparion/templates/register/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Thrive | Login{% endblock %}
{% block content %}
<div id="affiliate-login" class="container">
		<ul class="breadcrumb">
			<li><a href="/">Home</a></li>
			<li><a href="">Account</a></li>
			<li><a href="">Login</a></li>
		</ul>	
	<div class="row">
		<div id="content" class="col-sm-12">
				<div class="row">
				<div class="col-sm-6">
					<div class="well">
						<h2>Register Here</h2>
						<p>
							<p>I am not currently a customer.</p>
							<p>Click Continue below to create a customer account.</p>
						</p>
						<a class="btn btn-primary" href="{% url 'store:registeration' %}">Continue</a>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="well">
						<h2>Login</h2>
						<form action="" method="POST" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="form-group">
								<label class="control-label" for="input-email">E-Mail</label>
								<input type="text" name="{{ login_form.email.name }}" value="" placeholder="Enter E-Mail"
									id="input-email" class="form-control" required/>
							</div>
							<div class="form-group">
								<label class="control-label" for="input-password">Password</label>
								<input type="password" name="{{ login_form.password.name }}" value="" placeholder="Enter Password"
									id="input-password" class="form-control" required/><br>
								<a href="">Forgot Password</a>
							</div>
							<input type="submit" value="Login" class="btn btn-primary" />
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

koparion/templates/register/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Thrive | Register{% endblock %}

{% block content %}
<div id="affiliate-login" class="container">
    <ul class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'store:login' %}">Login</a></li>
    </ul>	
</div>
<div class="main-row">
    <div class="container">
        <div class="row">
            <div class="main-col col-sm-12 col-md-12">
                <div class="row sub-row">
                    <div">
                        <div class="col-lg-6 col-offset-2">
                            <div class="well">
                                <form action="" method="POST" enctype="multipart/form-data">
									{% csrf_token %}
									<div class="form-group">
										<label class="control-label" for="input-email">E-Mail</label>
										<input type="email" name="{{ registration_form.email.name }}" value="" placeholder="Enter E-Mail"
											id="input-email" class="form-control" required/>
									</div>
                                    <div class="form-group">
										<label class="control-label" for="input-name">Full Name</label>
										<input type="text" name="{{ registration_form.name.name }}" value="" placeholder="Enter Fullname"
											id="input-text" class="form-control" required/>
                                    </div>
                                    <div class="form-group">
										<label class="control-label" for="input-telephone">Phone Number</label>
										<input type="text" name="{{ registration_form.telephone.name }}" value="" placeholder="Telephone Number"
											id="input-text" class="form-control" required/>
                                    </div>
									<div class="form-group">
										<label class="control-label" for="input-password">Password</label>
										<input type="password" name="{{ registration_form.password1.name }}" value="" placeholder="Password"
											id="input-password" class="form-control" required/>
                                    </div>
                                    <div class="form-group">
										<label class="control-label" for="input-password">Re-Enter Password</label>
										<input type="password" name="{{ registration_form.password2.name }}" value="" placeholder="Re-Type Password"
											id="input-password" class="form-control" required/>
                                    </div>

									<input type="submit" value="Register" class="btn btn-primary" />
									<input type="hidden" name="redirect"
										value="" />
								</form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}