koparion/koparion/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

koparion/store/urls.py
from django.urls import path

from . import views

app_name = 'store'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('search/', views.SearchPageView.as_view(), name='search'), # url to search page
    path('all-books/', views.AllBooksPageView.as_view(), name='all_books'), #a url to all books
    path('book/id/slug/', views.DetailPageView.as_view(), name='book_detail'), # url to a specific book
    path('register/', views.register, name='registeration'), # url to user registration page
    path('login/', views.login_view, name='login'), # url to user login page
    path('logout/', views.logout_view, name='logout'),


    path('cart-add/', views.cart_add, name='cart_add'), # adding books to the cart
    path('cart-summary/', views.cart_summary, name='cart_summary'), # summary of the cart
    path('checkout/', views.checkout_view, name='checkout'),
]

koparion/templates/footer.html
{% load static %}
<footer>

    <div class="footer-top">
        <div class="container">
            <ul class="links-footer">
                <li><a href="/">home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="{% url 'store:all_books' %}">Shop</a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="#">Affiliate</a></li>
                <li><a href="#">Site Map</a></li>
            </ul>


            <div class="row">

                <div class="col-md-3 col-sm-6 col-footer">
                    <div class="footer-title">
                        <h5>Information</h5>
                    </div>
                    <div class="footer-content">
                        <ul class="list-unstyled text-content">
                            <li><a href="#">About
                                    Us</a></li>
                            <li><a href="#">Delivery
                                    Information</a></li>
                            <li><a href="#">Privacy
                                    Policy</a></li>
                            <li><a href="#">Terms
                                    &amp; Conditions</a></li>
                            <li><a href="#">Gift Certificates</a></li>

                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 col-footer">
                    <div class="footer-title">
                        <h5>Customer Service</h5>
                    </div>
                    <div class="footer-content">
                        <ul class="list-unstyled text-content">
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Returns</a></li>
                            <li><a href="#">Site Map</a></li>
                            <li><a href="#">Order History</a></li>
                            <li><a href="#">Wish List</a></li>

                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 col-footer">
                    <div class="footer-title">
                        <h5>Extras</h5>
                    </div>
                    <div class="footer-content">
                        <ul class="list-unstyled text-content">
                            <li><a href="#">Brands</a></li>
                            <li><a href="#">Gift Certificates</a></li>
                            <li><a href="#">Affiliate</a></li>
                            <li><a href="#">Specials</a></li>
                            <li><a href="#">My Account</a></li>

                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 col-footer">
                    <div class="footer-title">
                        <h5>STORE INFORMATION</h5>
                    </div>

                    <div class="footer-content">
                        <div class="footer-contact">
                            <p class="adress"><span>My Company </span>42 avenue des Champs Elysées 75000 Paris
                                France</p>
                            <p><span>Call us now:</span> (+1)866-540-3229</p>
                            <p><span>Email:</span> support@plazathemes.com</p>
                        </div>
                    </div>



                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="container-inner">
                <div class="footer-copyright">
                    <p>Copyright &copy; 2018 <a href="http://www.plazathemes.com/">PlazaThemes</a>.<span>All
                            Right Reserved.</span></p>
                </div>
                <div class="payment">
                    <img src="{% static 'image/catalog/cmsblock/payment.png' %}" alt="payment">
                </div>

            </div>
        </div>
    </div>
    <div id="back-top"><i class="fa fa-angle-up"></i></div>
</footer>
<script>
    $(document).ready(function () {
        // hide #back-top first
        $("#back-top").hide();
        // fade in #back-top
        $(function () {
            $(window).scroll(function () {
                if ($(this).scrollTop() > $('body').height() / 3) {
                    $('#back-top').fadeIn();
                } else {
                    $('#back-top').fadeOut();
                }
            });
            // scroll body to 0px on click
            $('#back-top').click(function () {
                $('body,html').animate({
                    scrollTop: 0
                }, 800);
                return false;
            });
        });
    });
</script>