koparion/koparion/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

koparion/store/urls.py
from django.urls import path

from . import views

app_name = 'store'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('search/', views.SearchPageView.as_view(), name='search'), # url to search page
    path('all-books/', views.AllBooksPageView.as_view(), name='all_books'), #a url to all books
    path('book/id/slug/', views.DetailPageView.as_view(), name='book_detail'), # url to a specific book
    path('register/', views.register, name='registeration'), # url to user registration page
    path('login/', views.login_view, name='login'), # url to user login page
    path('logout/', views.logout_view, name='logout'),


    path('cart-add/', views.cart_add, name='cart_add'), # adding books to the cart
    path('cart-summary/', views.cart_summary, name='cart_summary'), # summary of the cart
    path('checkout/', views.checkout_view, name='checkout'),
]

koparion/templates/search/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ searched }}{% endblock %}
{% block content %}
<div class="container layer-category">
	<div class="layered-navigation-block"></div>
	<!-- <div class="ajax-loader">
		<img src="{% static 'image/catalog/AjaxLoader.gif' %}" alt="" />
	</div> -->

	<ul class="breadcrumb">
		<li><a href="/">Home</a></li>
		<li><a href="">Casual</a></li>
	</ul>
	<div class="row">
		<div class="col-order">
			<div id="content" class="col-md-9 col-sm-12">
				<div class="category-info">


					<h1 class="category-name">Casual</h1>



				</div>
				<div class="custom-category">
					<!-- <div><a href="index6431.html?route=product/compare" id="compare-total">Product Compare
							(0)</a></div> -->

					<div class="toolbar toolbar-products">
						<div class="modes">
							<div class="btn-group">
								<button type="button" id="grid-view" class="btn">Grid</button>
								<button type="button" id="list-view" class="btn">List</button>
							</div>
						</div>
						<div class="toolbar-amount">
							<span>Showing 1 to 3 of 3 (1 Pages)</span>
						</div>
					</div>
					<div class="custom-products">
						<div class="row">
							<div class="product-layout product-list">
								<div class="product-thumb">
									<div class="item item1">
										<div class="item-inner">
											<div class="col-image">
												<div class="image images-container">
													<a href="{% url 'store:book_detail' %}"
														class="product-image">
														<img src="{% static 'image/cache/catalog/product/Book/13-600x770.jpg' %}"
															alt="Crown Summit Backpacks" title="Crown Summit Backpacks"
															class="img-responsive" />
													</a>
													<button class="button btn-quickview" type="button"
														title="Quick View"
														onclick="ocquickview.ajaxView('index8237.html?route=product/product&amp;path=241&amp;product_id=91')"><span>Quick
															View</span></button>

												</div>
											</div>
											<div class="col-des">
												<div class="caption">
													<p class="manufacture-product">
														<a
															href="index8be0.html?route=product/manufacturer/info&amp;manufacturer_id=10">Sony</a>
													</p>

													<div class="ratings">
														<div class="rating-box">
															<div class="rating1">rating</div>
														</div>
													</div>
													<h4 class="product-name"><a
															href="{% url 'store:book_detail' %}">Crown
															Summit Backpacks</a></h4>
													<div class="price-box">
														<label>Price:</label>
														<p class="regular-price"><span class="price">$1,202.00</span>
														</p>
														<p class="price-tax"><span class="price">Ex Tax:
																$1,000.00</span></p>
													</div>

													<p class="product-des">Unprecedented power. The next
														generation of processing technology has arrived. Built
														into the newest VAIO notebooks lies Intel&#39;s latest,
														most powerful innovation yet: Intel&reg; Centrino&reg; 2
														processor technology. Boasting incredible speed,
														expanded wireless connectivity, enhanced multimedia s..
													</p>

													<!-- <div class="action-links">
														<button class="button btn-cart" type="button"
															title="Add to Cart" onclick="cart.add('91', '1')"><span>Add
																to
																Cart</span></button>
														<div class="add-to-links">
															<button class="button btn-wishlist" type="button"
																title="Add to Wish List"
																onclick="wishlist.add('91');"><span>Add to Wish
																	List</span></button>
															<button class="button btn-compare" type="button"
																title="Compare this Product"
																onclick="compare.add('91');"><span>Compare this
																	Product</span></button>

														</div>
													</div> -->

												</div>
											</div>
										</div>
									</div>
								</div>

							</div>
							<div class="product-layout product-list">
								<div class="product-thumb">
									<div class="item item2">
										<div class="item-inner">
											<div class="col-image">
												<div class="image images-container">
													<a href="{% url 'store:book_detail' %}"
														class="product-image">
														<img src="{% static 'image/cache/catalog/product/Book/15-600x770.jpg' %}"
															alt="Endeavor Daytrip Backpacks"
															title="Endeavor Daytrip Backpacks" class="img-responsive" />
													</a>
													<button class="button btn-quickview" type="button"
														title="Quick View"
														onclick="ocquickview.ajaxView('index042a.html?route=product/product&amp;path=241&amp;product_id=93')"><span>Quick
															View</span></button>

												</div>
											</div>
											<div class="col-des">
												<div class="caption">
													<p class="manufacture-product">
														<a
															href="index98fa.html?route=product/manufacturer/info&amp;manufacturer_id=8">Apple</a>
													</p>

													<div class="ratings">
														<div class="rating-box">
															<div class="rating3">rating</div>
														</div>
													</div>
													<h4 class="product-name"><a
															href="{% url 'store:book_detail' %}">Endeavor
															Daytrip Backpacks</a></h4>
													<div class="price-box">
														<label>Price:</label>
														<p class="regular-price"><span class="price">$98.00</span></p>
														<p class="price-tax"><span class="price">Ex Tax:
																$80.00</span></p>
													</div>

													<p class="product-des">More room to move.

														With 80GB or 160GB of storage and up to 40 hours of
														battery life, the new iPod classic lets you enjoy up to
														40,000 songs or up to 200 hours of video or any
														combination wherever you go.

														Cover Flow.

														Browse through your music collection by flipping through
														alb..</p>

													<!-- <div class="action-links">
														<button class="button btn-cart" type="button"
															title="Add to Cart" onclick="cart.add('93', '1')"><span>Add
																to
																Cart</span></button>
														<div class="add-to-links">
															<button class="button btn-wishlist" type="button"
																title="Add to Wish List"
																onclick="wishlist.add('93');"><span>Add to Wish
																	List</span></button>
															<button class="button btn-compare" type="button"
																title="Compare this Product"
																onclick="compare.add('93');"><span>Compare this
																	Product</span></button>

														</div>
													</div> -->

												</div>
											</div>
										</div>
									</div>
								</div>

							</div>
							<div class="product-layout product-list">
								<div class="product-thumb">
									<div class="item item3">
										<div class="item-inner">
											<div class="col-image">
												<div class="image images-container">
													<a href="{% url 'store:book_detail' %}"
														class="product-image">
														<img src="{% static 'image/cache/catalog/product/Book/16-600x770.jpg' %}"
															alt="Fusion Backpacks" title="Fusion Backpacks"
															class="img-responsive" />
													</a>
													<div class="label-product label_new">New</div>
													<button class="button btn-quickview" type="button"
														title="Quick View"
														onclick="ocquickview.ajaxView('index34ad.html?route=product/product&amp;path=241&amp;product_id=94')"><span>Quick
															View</span></button>

												</div>
											</div>
											<div class="col-des">
												<div class="caption">
													<p class="manufacture-product">
														<a
															href="index98fa.html?route=product/manufacturer/info&amp;manufacturer_id=8">Apple</a>
													</p>

													<div class="ratings">
														<div class="rating-box">
															<div class="rating4">rating</div>
														</div>
													</div>
													<h4 class="product-name"><a
															href="{% url 'store:book_detail' %}">Fusion
															Backpacks</a></h4>
													<div class="price-box">
														<label>Price:</label>
														<p class="regular-price"><span class="price">$98.00</span></p>
														<p class="price-tax"><span class="price">Ex Tax:
																$80.00</span></p>
													</div>

													<p class="product-des">Video in your pocket.

														Its the small iPod with one very big idea: video. The
														worlds most popular music player now lets you enjoy
														movies, TV shows, and more on a two-inch display thats
														65% brighter than before.

														Cover Flow.

														Browse through your music collection by flipping through
														albu..</p>

													<!-- <div class="action-links">
														<button class="button btn-cart" type="button"
															title="Add to Cart" onclick="cart.add('94', '1')"><span>Add
																to
																Cart</span></button>
														<div class="add-to-links">
															<button class="button btn-wishlist" type="button"
																title="Add to Wish List"
																onclick="wishlist.add('94');"><span>Add to Wish
																	List</span></button>
															<button class="button btn-compare" type="button"
																title="Compare this Product"
																onclick="compare.add('94');"><span>Compare this
																	Product</span></button>

														</div>
													</div> -->

												</div>
											</div>
										</div>
									</div>
								</div>

							</div>
						</div>
					</div>
					<div class="toolbar toolbar-products toolbar-bottom">
						<div class="toolbar-amount"><span>Showing 1 to 3 of 3 (1 Pages)</span></div>
						<div class="pages"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}